import type { Game, Prop, MiddleOpportunity, LineMovement } from "./types"

export const mockGames: Game[] = [
  {
    id: "lal-bos-1",
    sport: "NBA",
    homeTeam: {
      name: "Boston Celtics",
      abbreviation: "BOS",
    },
    awayTeam: {
      name: "Los Angeles Lakers",
      abbreviation: "LAL",
    },
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(), // 2 hours from now
    venue: "TD Garden",
    tvChannel: "ESPN",
    propCount: 52,
    evPlayCount: 5,
    topEvPlay: {
      playerName: "LeBron James",
      stat: "Points",
      line: 25.5,
      play: "UNDER",
      winProbability: 58.2,
      evPercentage: 3.9,
    },
  },
  {
    id: "mia-nyk-1",
    sport: "NBA",
    homeTeam: {
      name: "New York Knicks",
      abbreviation: "NYK",
    },
    awayTeam: {
      name: "Miami Heat",
      abbreviation: "MIA",
    },
    startTime: new Date(Date.now() + 1.5 * 60 * 60 * 1000).toISOString(),
    venue: "Madison Square Garden",
    tvChannel: "TNT",
    propCount: 48,
    evPlayCount: 3,
    topEvPlay: {
      playerName: "Jalen Brunson",
      stat: "Points",
      line: 27.5,
      play: "OVER",
      winProbability: 56.8,
      evPercentage: 2.5,
    },
  },
  {
    id: "gsw-phx-1",
    sport: "NBA",
    homeTeam: {
      name: "Phoenix Suns",
      abbreviation: "PHX",
    },
    awayTeam: {
      name: "Golden State Warriors",
      abbreviation: "GSW",
    },
    startTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    venue: "Footprint Center",
    tvChannel: "TNT",
    propCount: 55,
    evPlayCount: 7,
    topEvPlay: {
      playerName: "Stephen Curry",
      stat: "3-Ptrs",
      line: 5.5,
      play: "OVER",
      winProbability: 56.1,
      evPercentage: 1.8,
    },
  },
  {
    id: "tor-bos-nhl-1",
    sport: "NHL",
    homeTeam: {
      name: "Boston Bruins",
      abbreviation: "BOS",
    },
    awayTeam: {
      name: "Toronto Maple Leafs",
      abbreviation: "TOR",
    },
    startTime: new Date(Date.now() + 1.5 * 60 * 60 * 1000).toISOString(),
    venue: "TD Garden",
    tvChannel: "ESPN+",
    propCount: 28,
    evPlayCount: 2,
    topEvPlay: {
      playerName: "Auston Matthews",
      stat: "Points",
      line: 0.5,
      play: "OVER",
      winProbability: 55.3,
      evPercentage: 2.1,
    },
  },
]

export const mockProps: Prop[] = [
  {
    id: "lebron-points-1",
    playerName: "LeBron James",
    teamAbbr: "LAL",
    opponentAbbr: "BOS",
    game: "LAL@BOS",
    gameTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    sport: "NBA",
    stat: "Points",
    lines: {
      prizepicks: 25.5,
      underdog: 24.5,
      sleeper: 25.0,
      betr: null,
    },
    bestPlay: {
      platform: "Underdog",
      play: "OVER",
      line: 24.5,
      winProbability: 58.2,
      evPercentage: 3.9,
    },
    sharpOdds: {
      book: "FanDuel",
      line: 25.5,
      overOdds: -140,
      underOdds: 110,
      overImplied: 58.3,
      underImplied: 47.6,
      noVigOverProb: 55.0,
      noVigUnderProb: 45.0,
    },
  },
  {
    id: "rj-rebounds-1",
    playerName: "RJ Barrett",
    teamAbbr: "TOR",
    opponentAbbr: "IND",
    game: "TOR@IND",
    gameTime: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    sport: "NBA",
    stat: "Rebounds",
    lines: {
      prizepicks: 6.5,
      underdog: 7.0,
      sleeper: null,
      betr: null,
    },
    bestPlay: {
      platform: "PrizePicks",
      play: "UNDER",
      line: 6.5,
      winProbability: 57.4,
      evPercentage: 3.1,
    },
    sharpOdds: {
      book: "DraftKings",
      line: 6.5,
      overOdds: -110,
      underOdds: -110,
      overImplied: 52.4,
      underImplied: 52.4,
      noVigOverProb: 50.0,
      noVigUnderProb: 50.0,
    },
  },
  {
    id: "curry-3ptrs-1",
    playerName: "Stephen Curry",
    teamAbbr: "GSW",
    opponentAbbr: "PHX",
    game: "GSW@PHX",
    gameTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    sport: "NBA",
    stat: "3-Ptrs",
    lines: {
      prizepicks: 5.5,
      underdog: 5.5,
      sleeper: 5.0,
      betr: null,
    },
    bestPlay: {
      platform: "Sleeper",
      play: "OVER",
      line: 5.0,
      winProbability: 56.1,
      evPercentage: 1.8,
    },
    sharpOdds: {
      book: "FanDuel",
      line: 5.5,
      overOdds: -130,
      underOdds: 100,
      overImplied: 56.5,
      underImplied: 50.0,
      noVigOverProb: 53.0,
      noVigUnderProb: 47.0,
    },
  },
  {
    id: "maxey-points-1",
    playerName: "Tyrese Maxey",
    teamAbbr: "PHI",
    opponentAbbr: "MIA",
    game: "PHI@MIA",
    gameTime: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    sport: "NBA",
    stat: "Points",
    lines: {
      prizepicks: 24.5,
      underdog: 24.5,
      sleeper: 24.5,
      betr: 24.5,
    },
    bestPlay: undefined,
    sharpOdds: {
      book: "DraftKings",
      line: 24.5,
      overOdds: -115,
      underOdds: -105,
      overImplied: 53.5,
      underImplied: 51.2,
      noVigOverProb: 49.0,
      noVigUnderProb: 51.0,
    },
  },
]

export const mockMiddles: MiddleOpportunity[] = [
  {
    id: "middle-1",
    playerName: "LeBron James",
    statType: "Points",
    gameInfo: "LAL @ BOS",
    gameTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    platformA: {
      name: "PrizePicks",
      line: 25.5,
      recommendedPlay: "UNDER",
    },
    platformB: {
      name: "Underdog",
      line: 24.5,
      recommendedPlay: "OVER",
    },
    middleZone: [25],
    spreadSize: 1.0,
  },
  {
    id: "middle-2",
    playerName: "Tyrese Maxey",
    statType: "Points",
    gameInfo: "PHI @ MIA",
    gameTime: new Date(Date.now() + 2.5 * 60 * 60 * 1000).toISOString(),
    platformA: {
      name: "Sleeper",
      line: 25.0,
      recommendedPlay: "UNDER",
    },
    platformB: {
      name: "PrizePicks",
      line: 24.5,
      recommendedPlay: "OVER",
    },
    middleZone: [25],
    spreadSize: 0.5,
  },
]

export const mockLineMovements: LineMovement[] = [
  {
    id: "movement-1",
    playerName: "LeBron James",
    statType: "Points",
    gameInfo: "LAL @ BOS",
    gameTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    minutesAgo: 30,
    movements: [
      {
        platform: "PrizePicks",
        oldLine: 26.5,
        newLine: 25.5,
        change: -1.0,
      },
      {
        platform: "Underdog",
        oldLine: 25.5,
        newLine: 24.5,
        change: -1.0,
      },
    ],
    analysis: "Sharp action on UNDER - Line dropped across all books",
  },
  {
    id: "movement-2",
    playerName: "Stephen Curry",
    statType: "3-Pointers",
    gameInfo: "GSW @ PHX",
    gameTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    minutesAgo: 45,
    movements: [
      {
        platform: "PrizePicks",
        oldLine: 5.0,
        newLine: 5.5,
        change: 0.5,
      },
      {
        platform: "Underdog",
        oldLine: 5.5,
        newLine: 5.5,
        change: 0,
      },
    ],
    analysis: "PrizePicks adjusted up - May have +EV on Underdog OVER now",
  },
]
